### ISSUE TITLE
Hyperparameters about Cora and Citeseer

### ISSUE THREAD

**Issue by rockcor** [BangHonor/SimGC#1]
Thanks for your consice solution on Graph Condensation. I locally run your code and most of results reported on paper can be achieved. 

The question is I cannot reproduce Cora and Citeseer. I got 76 of Cora and 62 of Citeseer. Also, the hyperparameters of Citeseer are missed in the code.

**Comment by BangHonor** [comment]
Hello ,thanks for your interest in our work. Please make sure that on these two datasets, you are using the&nbsp;SGC_Multi_PYG model, which contains a MLP instead of Linear layer inside. Besides, these two datasets are too small and they are highly sensitive to hyperparameters, so you can further tune the layers/hidden units of SGC and the evalutaion GNN, condensing_loop and leanring rates.


                       
Original Email
                       
                     

From:"Rock"< ***@***.*** &gt;;

Sent Time:2024/8/8 10:25

To:"BangHonor/SimGC"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[BangHonor/SimGC] Hyperparameters about Cora and Citeseer (Issue #1)




 
Thanks for your consice solution on Graph Condensation. I locally run your code and most of results reported on paper can be achieved.
 
The question is I cannot reproduce Cora and Citeseer. I got 76 of Cora and 62 of Citeseer. Also, the hyperparameters of Citeseer are missed in the code.

**Comment by BangHonor** [comment]
Besides, the citeseer hypermeters are the same as cora. If you get bad results using the same hyperparameters, please pay attention the to points I mentioned in the last e-mail. The results of these two datasets are rather unstable and they are too small to proceed graph condensation.&nbsp;






                       
Original Email
                       
                     

From:"Rock"< ***@***.*** &gt;;

Sent Time:2024/8/8 10:25

To:"BangHonor/SimGC"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[BangHonor/SimGC] Hyperparameters about Cora and Citeseer (Issue #1)




 
Thanks for your consice solution on Graph Condensation. I locally run your code and most of results reported on paper can be achieved.
 
The question is I cannot reproduce Cora and Citeseer. I got 76 of Cora and 62 of Citeseer. Also, the hyperparameters of Citeseer are missed in the code.
